spin_manifest_version = 2

[application]
name = "wasm-spin"
version = "0.1.0"
authors = ["Daiki Tamura <dtamura23@outlook.jp>"]
description = ""


[[trigger.http]]
route = "/wasm/go"
component = "hello-go"

[component.hello-go]
source = "hello-go/main.wasm"
allowed_outbound_hosts = []
[component.hello-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
workdir = "hello-go"
watch = ["**/*.go", "go.mod"]
