process_names:
  - name: "{{.ExeBase}};{{.PID}};{{.Username}};{{.Matches.cmdline}}"
    comm:
      - app # golang
    cmdline: 
    - (?P<cmdline>.*)
  - name: "{{.ExeBase}};{{.PID}};{{.Username}};{{.Matches.cmdline}}"
    cmdline: 
    - (?P<cmdline>.*\/nodejs\/bin\/node.*)
  - name: "{{.ExeBase}};{{.PID}};{{.Username}};{{.Matches.cmdline}}"
    cmdline: 
    - (?P<cmdline>.*spin.*)